#!/usr/bin/env sh

# bar settings
yabai -m config status_bar                   off
yabai -m config status_bar_text_font         "Helvetica Neue:Bold:12.0"
yabai -m config status_bar_icon_font         "FontAwesome:Regular:12.0"
yabai -m config status_bar_background_color  0xff202020
yabai -m config status_bar_foreground_color  0xffa8a8a8
yabai -m config status_bar_space_icon_strip  I II III IV V VI VII VIII IX X
yabai -m config status_bar_power_icon_strip   
yabai -m config status_bar_space_icon        
yabai -m config status_bar_clock_icon        

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_opacity               off
yabai -m config window_shadow                on
## 显示边框，default: off
yabai -m config window_border                on
yabai -m config window_border_width          4
yabai -m config active_window_border_color   0xff9c5054
yabai -m config normal_window_border_color   0xff505050
yabai -m config insert_window_border_color   0xffd75f5f
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
## 顶部边距，default: 20
yabai -m config top_padding                  2
## 底部边距，default: 20
yabai -m config bottom_padding               2
## 左边距，default: 20
yabai -m config left_padding                 2
## 右边距，default: 20
yabai -m config right_padding                2
## 窗体之间间距，default: 10
yabai -m config window_gap                   2


# float apps
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^系统偏好设置$" manage=off
yabai -m rule --add app="^WeChat$" manage=off
yabai -m rule --add app="^微信$" manage=off
yabai -m rule --add app="^QQ$" manage=off
yabai -m rule --add app="^Activity Monitor$" manage=off
yabai -m rule --add app="^活动监视器$" manage=off
yabai -m rule --add app="^EuDic$" manage=off
yabai -m rule --add app="^欧路词典$" manage=off
yabai -m rule --add app="^Surge$" manage=off
yabai -m rule --add app="^Surge 3$" manage=off
yabai -m rule --add app="^Surge$" manage=off
yabai -m rule --add app="^Surge Dashboard$" manage=off
yabai -m rule --add app="^OmniFocus$" manage=off
yabai -m rule --add app="^1Password 7$" manage=off
yabai -m rule --add app="^1Password Updater$" manage=off
yabai -m rule --add app="^Spark$" manage=off
yabai -m rule --add app="^网易云音乐$" manage=off
yabai -m rule --add app="^NeteaseMusic$" manage=off
yabai -m rule --add app="^IINA$" manage=off
yabai -m rule --add app="^访达$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^预览$" manage=off
yabai -m rule --add app="^Preview$" manage=off
yabai -m rule --add app="^App Store$" manage=off
yabai -m rule --add app="^Setapp$" manage=off
yabai -m rule --add app="^Timing$" manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off
yabai -m rule --add app="^Microsoft AutoUpdate$" manage=off
yabai -m rule --add app="^字体册$" manage=off
yabai -m rule --add app="^Font Book$" manage=off
yabai -m rule --add app="^TeamViewer$" manage=off
yabai -m rule --add app="^日历$" manage=off
yabai -m rule --add app="^Calendar$" manage=off
yabai -m rule --add app="^印象笔记$" manage=off
yabai -m rule --add app="^calibre$" manage=off
yabai -m rule --add app="^E-book Viewer$" manage=off
yabai -m rule --add app="^PhotoBulk$" manage=off
yabai -m rule --add app="^Squash$" manage=off
yabai -m rule --add app="^Beyond Compare$" manage=off
yabai -m rule --add app="^Dash$" manage=off
yabai -m rule --add app="^Microsoft Excel$" manage=off
yabai -m rule --add app="^Microsoft Word$" manage=off
yabai -m rule --add app="^Microsoft PowerPoint$" manage=off
yabai -m rule --add app="^KeyKey Typing Tutor$" manage=off
yabai -m rule --add app="^KeyKey$" manage=off
yabai -m rule --add app="^相册$" manage=off
yabai -m rule --add app="^Phontos$" manage=off
yabai -m rule --add app="^Zoom$" manage=off
yabai -m rule --add app="^zoom.us$" manage=off


echo "yabai configuration loaded.."
