#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config window_shadow                on
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.95
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
## border config
yabai -m config window_border on
yabai -m config window_border_width 4
# yabai -m config active_window_border_color 0xff9c5054
# yabai -m config active_window_border_color 0xff8b5d5f
yabai -m config active_window_border_color 0xffA98175
# yabai -m config normal_window_border_color 0xff555555
# 设置为完全透明，解决在 idea 里面代码提示框快速闪动
# 造成的边框线错位
yabai -m config normal_window_border_color 0x00555555

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  4
yabai -m config bottom_padding               4
yabai -m config left_padding                 4
yabai -m config right_padding                4
yabai -m config window_gap                   4

# float apps
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^系统偏好设置$" manage=off
yabai -m rule --add app="^WeChat$" manage=off
yabai -m rule --add app="^WeCom$" manage=off
yabai -m rule --add app="^企业微信$" manage=off
yabai -m rule --add app="^Docker Desktop$" manage=off
yabai -m rule --add app="^TencentMeeting$" manage=off
yabai -m rule --add app="^微信$" manage=off
yabai -m rule --add app="^QQ$" manage=off
yabai -m rule --add app="^Activity Monitor$" manage=off
yabai -m rule --add app="^活动监视器$" manage=off
yabai -m rule --add app="^EuDic$" manage=off
yabai -m rule --add app="^欧路词典$" manage=off
yabai -m rule --add app="^Surge$" manage=off
yabai -m rule --add app="^Surge 3$" manage=off
yabai -m rule --add app="^Surge$" manage=off
yabai -m rule --add app="^Surge Dashboard$" manage=off
yabai -m rule --add app="^OmniFocus$" manage=off
yabai -m rule --add app="^1Password 7$" manage=off
yabai -m rule --add app="^1Password Updater$" manage=off
yabai -m rule --add app="^Spark$" manage=off
yabai -m rule --add app="^网易云音乐$" manage=off
yabai -m rule --add app="^NeteaseMusic$" manage=off
yabai -m rule --add app="^IINA$" manage=off
yabai -m rule --add app="^访达$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^预览$" manage=off
yabai -m rule --add app="^Preview$" manage=off
yabai -m rule --add app="^App Store$" manage=off
yabai -m rule --add app="^Setapp$" manage=off
yabai -m rule --add app="^Timing$" manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off
yabai -m rule --add app="^Microsoft AutoUpdate$" manage=off
yabai -m rule --add app="^字体册$" manage=off
yabai -m rule --add app="^Font Book$" manage=off
yabai -m rule --add app="^TeamViewer$" manage=off
yabai -m rule --add app="^日历$" manage=off
yabai -m rule --add app="^Calendar$" manage=off
yabai -m rule --add app="^印象笔记$" manage=off
yabai -m rule --add app="^calibre$" manage=off
yabai -m rule --add app="^E-book Viewer$" manage=off
yabai -m rule --add app="^PhotoBulk$" manage=off
yabai -m rule --add app="^Squash$" manage=off
yabai -m rule --add app="^Beyond Compare$" manage=off
yabai -m rule --add app="^Dash$" manage=off
yabai -m rule --add app="^Microsoft Excel$" manage=off
yabai -m rule --add app="^Microsoft Word$" manage=off
yabai -m rule --add app="^Microsoft PowerPoint$" manage=off
yabai -m rule --add app="^KeyKey Typing Tutor$" manage=off
yabai -m rule --add app="^KeyKey$" manage=off
yabai -m rule --add app="^相册$" manage=off
yabai -m rule --add app="^Phontos$" manage=off
yabai -m rule --add app="^Zoom$" manage=off
yabai -m rule --add app="^zoom.us$" manage=off
yabai -m rule --add app="^QuickTime Player$" manage=off
yabai -m rule --add app="^DingTalk$" manage=off
yabai -m rule --add app="^VirtualBox$" manage=off
yabai -m rule --add app="^百度网盘$" manage=off
yabai -m rule --add app="^BaiduNetdisk$" manage=off
yabai -m rule --add app="^SaveWizard$" manage=off
yabai -m rule --add app="^Reminders$" manage=off
yabai -m rule --add app="^Keka$" manage=off
yabai -m rule --add app="^Books$" manage=off
yabai -m rule --add app="^Alfred Preferences$" manage=off
yabai -m rule --add app="^OneDrive$" manage=off
yabai -m rule --add app="^EasyConnect$" manage=off
yabai -m rule --add app="^Hidden Bar$" manage=off
yabai -m rule --add app="^System Information$" manage=off
yabai -m rule --add app="^Xnip$" manage=off
# yabai -m rule --add app="^VMware Fusion$" manage=off
yabai -m rule --add app="^Logi Options$" manage=off
yabai -m rule --add app="^PasteNow$" manage=off
yabai -m rule --add app="^Music$" manage=off
yabai -m rule --add app="^MotionPro$" manage=off
yabai -m rule --add app="^Shottr$" manage=off
yabai -m rule --add app="^Raycast$" manage=off

yabai -m rule --add app="^JetBrains Toolbox$" manage=off
jetbrain_apps="^(IntelliJ IDEA|WebStorm|PyCharm|CLion|GoLand)$"
yabai -m rule --add app="${jetbrain_apps}" title="^(Preferences|Project Structure|Plugins|Run/Debug Configurations|Edit configuration settings)$" manage=off

yabai -m rule --add title="(Copy|Bin|About This Mac|Info)" manage=off

echo "yabai configuration loaded.."
